[package]
name = "rcp"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive", "color"] }
indicatif = "0.17"
colored = "2.1"
walkdir = "2.4"
filetime = "0.2"
